# Generated by Django 3.1.5 on 2021-01-18 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('ficlity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('total_area', models.FloatField()),
                ('seats_area', models.FloatField()),
                ('waitting_area', models.FloatField()),
                ('seats_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DistanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_num', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', '開店中'), ('close', '閉店中')], default='close', max_length=8)),
                ('ficlity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_recode', to='recordApp.facility')),
            ],
        ),
    ]
