# Generated by Django 3.1.5 on 2021-01-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancerecord',
            name='ave_distance',
            field=models.FloatField(default=3.2),
            preserve_default=False,
        ),
    ]
