# Generated by Django 3.1.5 on 2021-01-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0002_distancerecord_ave_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distancerecord',
            old_name='ave_distance',
            new_name='avg_distance',
        ),
    ]
