# Generated by Django 3.1.5 on 2021-01-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0004_remove_distancerecord_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancerecord',
            name='status',
            field=models.CharField(choices=[('open', '開店中'), ('close', '閉店中')], default='close', max_length=10),
        ),
    ]
