# Generated by Django 3.1.5 on 2021-01-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0006_auto_20210119_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distancerecord',
            old_name='ficlity_id',
            new_name='facility_id',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='ficlity_id',
            new_name='facility_id',
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
